### PR TITLE
Skript

### PR DESCRIPTION
**Pull request by BubblePlayzTHEREAL**
I want Skript

### CODE REVIEW

**Review by ColdDev — CHANGES_REQUESTED** [review]
Please change the capitalization of this file to be lowercase, i.e. `skript.jar`.

**Comment by BubblePlayzTHEREAL** [comment]
k

**Comment by BubblePlayzTHEREAL** [comment]
I have fixed that.

**Review by ColdDev — APPROVED** [review]

**Comment by ColdDev** [comment]
LGTM, merged

**Pull request merged**
